---
efiSystemPartition: "/boot/efi"
efiSystemPartitionSize: 300M
userSwapChoices: [ none, file ]
defaultFileSystemType: "ext4"
availableFileSystemTypes: [ "ext4", "btrfs" ]
enableLuksAutomatedPartitioning: true
allowManualPartitioning: true
alwaysShowPartitionLabels: true
initialPartitioningChoice: none
initialSwapChoice: none
