---
defaultGroups: [ sudo, adm, cdrom, plugdev ]
autologinGroup: autologin
doAutologin: false
sudoersGroup: sudo
setRootPassword: false
passwordRequirements: { minLength: 8 }
allowWeakPasswords: false
userShell: /bin/bash
