# SCAFFOLD - untested
modules-search: [ local ]
sequence:
  - show:
      - welcome
      - locale
      - keyboard
      - partition
      - users
      - summary
  - exec:
      - partition
      - mount
      - unpackfs
      - machineid
      - fstab
      - locale
      - keyboard
      - users
      - bootloader
      - umount
  - show:
      - finished
branding: nx
prompt-install: true
dont-chroot: false
