# EXPERIMENTAL / UNTESTED Calamares configuration for NX. Not Secure Boot capable (uses plain grub-install).
---
modules-search: [ local ]
instances: []
sequence:
  - show: [ welcome, locale, keyboard, partition, users, summary ]
  - exec: [ partition, mount, unpackfs, machineid, fstab, locale, keyboard, users, initramfs, bootloader, shellprocess, umount ]
  - show: [ finished ]
branding: nx
prompt-install: true
dont-chroot: false
oem-setup: false
disable-cancel: false
disable-cancel-during-exec: true
quit-at-end: false
